export const DEMO_MODEL_SNAPSHOT = {
  models: [
    {
      name: 'EfficientNetV2B0 (Blood Cancer)',
      cancer_type: 'blood',
      architecture: 'EfficientNetV2B0',
      framework: 'Keras / TensorFlow',
      metrics: {
        accuracy: 0.94,
        sensitivity: 0.6,
        specificity: 0.88,
        precision: 0.8333,
        f1_score: 0.6977,
        auc_roc: 0.7828,
      },
    },
    {
      name: 'EfficientNetV2B1 (Uterine Cancer)',
      cancer_type: 'uterine',
      architecture: 'EfficientNetV2B1',
      framework: 'Keras / TensorFlow',
      metrics: {
        accuracy: 0.91,
        sensitivity: 0.0,
        specificity: 1.0,
        precision: 0.0,
        f1_score: 0.0,
        auc_roc: 0.5191,
      },
    },
    {
      name: 'YOLOv11-cls (Blood Cancer)',
      cancer_type: 'blood',
      architecture: 'YOLOv11n-cls',
      framework: 'Ultralytics / PyTorch',
      metrics: {
        accuracy: 0.6333,
        sensitivity: 0.3333,
        specificity: 0.9333,
        precision: 0.5833,
        f1_score: 0.7179,
        auc_roc: 0.7822,
      },
    },
    {
      name: 'YOLOv11-cls (Uterine Cancer)',
      cancer_type: 'uterine',
      architecture: 'YOLOv11n-cls',
      framework: 'Ultralytics / PyTorch',
      metrics: {
        accuracy: 0.78,
        sensitivity: 0.0,
        specificity: 0.8667,
        precision: 0.8864,
        f1_score: 0.8764,
        auc_roc: 0.32,
      },
    },
  ],
  metric_descriptions: {
    accuracy: 'Overall correct predictions',
    sensitivity: 'True positive rate (cancer correctly identified)',
    specificity: 'True negative rate (normal correctly identified)',
    precision: 'Of predicted cancers, how many are real',
    f1_score: 'Harmonic mean of precision and sensitivity',
    auc_roc: 'Area under the ROC curve',
  },
};
